{% set name = "caldav" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/caldav-{{ version }}.tar.gz
  sha256: f3fd9013f0ba6a593fa4475e63fc4053674c632fa7267fb46ae4ae0581c04eb5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - lxml
    - niquests
    - icalendar >=6.0.0
    - icalendar-searcher >=1.0.5,<2
    - recurring-ical-events >=2.0.0
    - dnspython
    - python-dateutil
    - typing-extensions
    - pyyaml

test:
  imports:
    - caldav
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - typing-extensions


about:
  home: https://github.com/python-caldav/caldav
  summary: CalDAV (RFC4791) client library
  license: GPL-3.0-only AND Apache-2.0
  license_file:
    - COPYING.APACHE
    - COPYING.GPL

extra:
  recipe-maintainers:
    - tdido
