{% set name = "caldav" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/caldav-{{ version }}.tar.gz
  sha256: 2dabc24e85ca3288a2ecc8ffc609ca413fd973644e1c77153a01834917433ac8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - lxml
    - niquests
    - icalendar
    - recurring-ical-events >=2.0.0
    - pytz
    - tzlocal
    - typing-extensions

test:
  imports:
    - caldav
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - typing-extensions


about:
  home: https://github.com/python-caldav/caldav
  summary: CalDAV (RFC4791) client library
  license: GPL-3.0-only AND Apache-2.0
  license_file:
    - COPYING.APACHE
    - COPYING.GPL

extra:
  recipe-maintainers:
    - tdido
