{% set name = "caldav" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/caldav-{{ version }}.tar.gz
  sha256: 4317131127d8793f740cff2fd256f369321fa49ad750f83d6f31780f7c16c67b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - vobject
    - lxml
    - requests
    - icalendar
    - recurring-ical-events >=2.0.0
    - pytz
    - tzlocal

test:
  imports:
    - caldav
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-caldav/caldav
  summary: CalDAV (RFC4791) client library
  license: GPL-3.0-only AND Apache-2.0
  license_file:
    - COPYING.APACHE
    - COPYING.GPL

extra:
  recipe-maintainers:
    - tdido
